services:
  nginx:
    image: nginx:latest
    container_name: nginx
    network_mode: "host"
    volumes:
      # conf files
      - ./nginx.conf:/etc/nginx/nginx.conf
      # logs
      - ./data/nginx/logs:/var/log/nginx
      # optional confs
      # Easy websocket config
      # Global settings
      # for hosts behind Cloudflare Tunnel
      - ./conf.d:/etc/nginx/conf.d            

# if not running on host network, expose ports      
#    ports:
#      - "80:80"
#      - "443:443"