server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: nginx_json_logs
    pipeline_stages:
      - json:
          expressions:
            remote_addr: remote_addr
            remote_user: remote_user
            time_local: time_local
            time_iso8601: time_iso8601
            request: request
            request_uri: request_uri
            body_bytes_sent: body_bytes_sent
            http_referer: http_referer
            http_user_agent: http_user_agent
            http_x_forwarded_for: http_x_forwarded_for
            request_method: request_method
            status: status
            request_time: request_time
            server_name: server_name
            ssl_protocol: ssl_protocol
            ssl_cipher: ssl_cipher
            geoip2_data_country_code: geoip2_data_country_code
            geoip2_data_country_name: geoip2_data_country_name
            geoip2_data_city_name: geoip2_data_city_name
            geoip2_data_region_name: geoip2_data_region_name
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx
          log_format: json
          __path__: /var/log/nginx/json_access.log
  # - job_name: nginx
  #   static_configs:
  #     - targets:
  #         - localhost
  #       labels:
  #         job: nginx_logs
  #         __path__: /var/log/nginx/access*.log