name: dbeaver
services:
  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    # Enterprise
    # image: dbeaver/cloudbeaver-ee:latest
    container_name: cloudbeaver
    restart: unless-stopped
    ports:
      - "8978:8978"
    volumes:
      - cloudbeaver_data:/opt/cloudbeaver/workspace
    networks: # <--- Add this
      - global_db_management_network
volumes:
  cloudbeaver_data:
    external: true
networks:
  global_db_management_network:
    external: true
