apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-config
  namespace: default
  labels:
    app: n8n-main
    tier: backend
    component: config
    version: "1.0.0"
data:
  DB_TYPE: "postgres"
  DB_HOST: "postgres-postgresql.default.svc.cluster.local"
  DB_PORT: "5432"
  DB_USER: "edhunter-dba"
  DB_PASSWORD: "T+OgxNkwHWhUm9UtTu5gGVigkBTJ4BI31iMTRIwHTkw="
  DB_DATABASE: "n8n"
  N8N_ENCRYPTION_KEY: "hzyafaBg1D9LM40014nTxyQqHmpUuz3mkaiGe55Sw6w="
  N8N_TRUST_PROXY: "1"
  N8N_PROXY_HOPS: "1"
  EXECUTION_MODE: "queue"
  QUEUE_BULL_REDIS_HOST: "redis-master.default.svc.cluster.local"
  QUEUE_BULL_REDIS_PORT: "6379"
  N8N_BASIC_AUTH_ACTIVE: "true"
  N8N_BASIC_AUTH_USER: "dameliatus@hotmail.com"
  N8N_BASIC_AUTH_PASSWORD: "mxegQdm6QKbfdN"
  GENERIC_TIMEZONE: "America/Bogota"
  WEB_HOOK_URL: "http://localhost/"
  WEB_HOOK_TEST_URL: "http://localhost/"
  #N8N_HOST: "http://localhost:5678"
  #N8N_PORT: "5678"
  #N8N_PROTOCOL: "http"
  #N8N_LOG_LEVEL: "info"
  #N8N_EDITOR_BASE_URL: "http://localhost:5678"